  name: Nigthly Build of MuleSoft Extension for CloudBlue Connect
  
  on:
    schedule:
      - cron: '0 2 * * *'

  jobs:
    nightly-build:
      runs-on: ubuntu-latest
      steps:
        - id: checkout-master
          name: Checkout master branch code
          uses: actions/checkout@v2

        - id: setup-jdk8
          name: Set up JDK 8
          uses: joschi/setup-jdk@v2
          with:
            java-version: 8
            architecture: x64

        - id: install-secret-key
          name: Install gpg secret key
          run: |
            cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
            gpg --list-secret-keys --keyid-format LONG

        - id: modify-maven-settings
          name: Add Server details
          uses: s4u/maven-settings-action@v2.4.0
          with:
            servers: '[{"id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_TOKEN }}"}]'

        - id: publish-to-central
          name: Publish to Central Repository
          run: |
            mvn -f gitBuildPom.xml --no-transfer-progress --batch-mode -Dserver.endpoint="${{ secrets.SERVER_ENDPOINT }}" -Dserver.token.vendor="${{ secrets.SERVER_TOKEN_VENDOR }}" -Dserver.token.provider="${{ secrets.SERVER_TOKEN_PROVIDER }}" -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} clean deploy
