name: Release a new version of CloudBlue Connect MuleSoft Extension
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: 8
          architecture: x64
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Add Server details
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: '[{"id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_TOKEN }}"}]'
      - id: publish-to-central
        name: Publish to Central Repository
        run: |
            mvn -f gitBuildPom.xml --no-transfer-progress --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} clean deploy
